name: Create PR After Release-Please

on:
  push:
    branches: [develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request to release
        uses: peter-evans/create-pull-request@v6
        with:
          source-branch: develop
          target-branch: release
          title: 'Merge develop into release after release-please PR'
          body: 'Automated PR to merge develop into release after release-please PR is merged.'
          token: ${{ secrets.MY_RELESE_PLEASE_TOKEN }}
